In [4]:
#created by Arun
# first import numpy package
import numpy as np
#To create an array
np.array([6,5,4,3])

array([6, 5, 4, 3])

In [5]:
#Nympy array is homogeneous
#if it has different types then it tries to upcaste it
np.array([4.8,5,6,8])
#here the int values are upcasted to float

array([4.8, 5. , 6. , 8. ])

In [6]:
#To explicitly set the data typ
np.array([1,2,3,4],dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [8]:
#To create multidimensional arrays
np.array([range(i,i+3) for i in range(1,9,3)])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#To fill all elements in an array with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
#To fill all elements in an array with ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,),dtype=int)

array([1, 1, 1])

In [19]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
# random values between 0 and 1
np.random.random((3, 3))

array([[0.08410354, 0.09507921, 0.01766371],
       [0.8771109 , 0.79409753, 0.05098281],
       [0.7756353 , 0.87161365, 0.04317347]])

In [24]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.88617654,  0.92725661, -0.71562274],
       [ 0.63840556, -1.12929088, -1.74457205],
       [ 0.15220557,  1.2175481 , -0.4814936 ]])

In [25]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 2, 2],
       [3, 1, 0],
       [3, 4, 2]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])